<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:property name="pi_const" value="3.14159265"/>

<!-- Chassis Dimensions -->
<xacro:property name="body_length" value="1"/>
<xacro:property name="body_height" value="0.3"/>
<xacro:property name="body_width" value="0.6"/>

<!-- Wheel Dimensions -->
<xacro:property name="r" value="0.15"/>
<xacro:property name="wheel_width" value="0.1"/>

<xacro:property name="height" value="${body_height/2 +r}"/>

<!-- Wheel Distance from Origin -->
<xacro:property name="s1" value="${2*r}"/>

<!-- Caster Wheel distance from origin -->
<xacro:property name="s2" value="${2*r}"/>

<!-- Wheel origin to centerline -->
<xacro:property name="s3" value="${body_width/2 + wheel_width/2}"/>

<!-- Mass Properties -->
 <xacro:property name="chassis_mass" value="2000"/>
 <xacro:property name="wheel_mass" value="200"/>
 <xacro:property name="caster_mass" value="100"/>

 <!-- Inertia Properties -->
  <xacro:property name="bodyx" value="${(1/12)*chassis_mass*(body_height*body_height+body_width*body_width)}"/>
  <xacro:property name="bodyy" value="${(1/12)*chassis_mass*(body_length*body_length+body_height*body_height)}"/>
  <xacro:property name="bodyz" value="${(1/12)*chassis_mass*(body_length*body_length+body_width*body_width)}"/>

  <xacro:property name="Iz_wheel" value="${0.5*wheel_mass*r*r}"/>
  <xacro:property name="I_wheel" value="${(1.0/12.0)*wheel_mass*(3.0*r*r+wheel_width*wheel_width)}"/>

  <xacro:property name="I_caster" value="${(2.0/5.0)*caster_mass*r*r}"/>

  <xacro:macro name="inertia_chassis">
    <inertial>
        <origin rpy="0 0 0" xyz="0 0 ${height}"/>
        <mass value="${chassis_mass}"/>
        <inertia ixx="${bodyx}" ixy="0.0" ixz="0.0" iyy="${bodyy}" iyz="0" izz="${bodyz}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="inertia_wheel">
    <inertial>
        <origin rpy="1.570795 0 0" xyz="0 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia ixx="${I_wheel}" ixy="0.0" ixz="0.0" iyy="${I_wheel}" iyz="0" izz="${Iz_wheel}"/>
    </inertial>
  </xacro:macro>

 <xacro:macro name="inertia_caster">
    <inertial>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="${caster_mass}"/>
        <inertia ixx="${I_caster}" ixy="0.0" ixz="0.0" iyy="${I_caster}" iyz="0" izz="${I_caster}"/>
    </inertial>
  </xacro:macro>

  <!-- Including Gazebo File -->
  <!-- <xacro:include filename="$(find autonav_bot)/model/robot.gazebo" /> -->

  <!-- Colours -->
   <material name="black">
        <color rgba="0 0 0 1"/>
    </material>
    <material name="yellow">
        <color rgba="1 1 0 1"/>
    </material>
    <material name="gray">
        <color rgba="0.5 0.5 0.5 1"/>
    </material>
    <material name="blue">
        <color rgba="0 0 1 1"/>
    </material>
    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>
    
</robot>